### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Abdulselam Taye",
  "email": "abdulselam@example.com",
  "password": "123456",
  "role": "RECRUITER"
}

### Login User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "abdulselam@example.com",
  "password": "123456"
}